default: all

all: sploit1 sploit2 sploit3 sploit4

sploit1: sploit1.c
	gcc -Wall -ggdb sploit1.c -o sploit1

sploit2: sploit2.c
	gcc -Wall -ggdb sploit2.c -o sploit2

sploit3: sploit3.c
	gcc -Wall -ggdb sploit3.c -o sploit3

sploit4: sploit4.c
	gcc -Wall -ggdb sploit4.c -o sploit4

run1: sploit1
	./sploit1
	
run2: sploit2
	./sploit2
	
run3: sploit3
	./sploit3
	
run4: sploit4
	./sploit4
	
gdb1: sploit1
	gdb sploit1
	
gdb2: sploit2
	gdb sploit2
	
gdb3: sploit3
	gdb sploit3
	
gdb4: sploit4
	gdb sploit4	
